This Magento image gallery extension free is compatible with all Magento stores. You can easily manage photo gallery on your site using this image gallery module.
<br/><br/>
<h1>Use block call on cms page </h1>
<b>
{{block type="imagegallery/imagegallery" name="imagegallery" template="imagegallery/test.phtml"}}
</b>
<br/>
<br/>
<h1>Features</h1>
1. Managing photos  gellary  (image galleries) <br/>
2. Easy uploading/removing photo galleries (multi-upload function) <br/>
3. Captions for all images Displaying image galleries in slideshows with beautiful modal dialogs (PrettyPhoto library)<br/>
4. SEO friendly image gallery URLs.<br/>
5.  Easy to customize layout of the photo galleries through backend.<br/>
6. 100% Open source.<br/>
7. Easy to install and use.<br/>
8. Support all version.
<br/>
<h1>Support </h1>
in.mukeshsaini@gmail.com<br/>

<br/>

<h1>Screenshot on Front-end</h1>
<img src="http://trimurtyinfotech.com/project/testm/img/screenshot3.png" width="700"/><br/>
<img src="http://trimurtyinfotech.com/project/testm/img/screenshot1.png"  width="700"/><br/>
 
<br/>

<h1>Screenshot on Back-end</h1>
<img src="http://trimurtyinfotech.com/project/testm/img/screenshot3admi1.png"  width="700"/><br/>
<img src="http://trimurtyinfotech.com/project/testm/img/screenshotadmin2.png"  width="700"/><br/>


